DASHBOARD_HTML = r"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/static/favicon.svg"><title>FetchHarbor Admin</title><style>
:root{color-scheme:dark;--panel:#101d2c;--line:#294057;--text:#e8f0f7;--muted:#91a4b8;--accent:#43d6b5;--warn:#f6c65b}*{box-sizing:border-box}body{margin:0;background:#08111d;color:var(--text);font:14px system-ui}.wrap{max-width:1300px;margin:auto;padding:28px}.top,.row{display:flex;justify-content:space-between;align-items:center;gap:12px}.top{margin-bottom:24px}.controls{display:flex;gap:12px}.muted,a{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:18px}.s4{grid-column:span 4}.s6{grid-column:span 6}.s8{grid-column:span 8}.s12{grid-column:span 12}.metric{font-size:28px;font-weight:700}.row{padding:9px 0;border-bottom:1px solid var(--line)}.warning{color:var(--warn)}.pass{color:var(--accent)}input,select{width:100%;background:#091522;border:1px solid var(--line);color:var(--text);padding:9px;border-radius:8px}label{display:block;color:var(--muted);margin:10px 0 5px}button{background:var(--accent);border:0;border-radius:8px;padding:10px 16px;font-weight:700;cursor:pointer}.login{display:flex;gap:8px}.login input{width:280px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid var(--line)}@media(max-width:850px){.s4,.s6,.s8{grid-column:span 12}.top,.controls{align-items:flex-start;flex-direction:column}}
</style></head><body><div class="wrap"><div class="top"><div><img src="/static/logo.svg" alt="FetchHarbor" width="190"><div class="muted">Operations, configuration and security</div></div><div class="controls"><a href="https://github.com/BenColeAu/fetchharbor" target="_blank" rel="noopener noreferrer">GitHub repository ↗</a><div class="login"><input id="token" type="password" placeholder="Admin token" autocomplete="off" autocapitalize="none" spellcheck="false"><button onclick="login()">Connect</button><button onclick="logout()">Logout</button></div></div></div><div id="content" class="grid"><section class="panel s12">Enter the admin token to load the protected control plane.</section></div></div>
<script>
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),headers=()=>{const h={'Content-Type':'application/json'},t=document.querySelector('#token').value;if(t)h['X-Admin-Token']=t;return h},fmt=b=>(b/1048576).toFixed(1)+' MiB';
async function api(path,opts={}){const r=await fetch('/admin/api/'+path,{...opts,headers:headers(),cache:'no-store',credentials:'same-origin',referrerPolicy:'no-referrer'});if(!r.ok)throw new Error((await r.json()).detail||r.statusText);return r.json()}
async function login(){try{await api('session',{method:'POST'});document.querySelector('#token').value='';await loadAll()}catch(e){alert(e.message)}}
async function logout(){try{await api('session',{method:'DELETE'});document.querySelector('#content').innerHTML='<section class="panel s12">Signed out. Enter the admin token to reconnect.</section>'}catch(e){alert(e.message)}}
async function loadAll(){try{const[o,c,s]=await Promise.all([api('overview'),api('configuration'),api('security')]);render(o,c,s)}catch(e){document.querySelector('#content').innerHTML=`<section class="panel s12 warning">${esc(e.message)}</section>`}}
function render(o,c,s){const rows=o.metrics.routes.map(x=>`<tr><td>${esc(x.route)}</td><td>${esc(x.requests)}</td><td>${esc(x.errors)}</td><td>${esc(x.last_status)}</td></tr>`).join('')||'<tr><td colspan="4">No requests yet</td></tr>',checks=s.checks.map(x=>`<div class="row"><div><b>${esc(x.name)}</b><div class="muted">${esc(x.detail)}</div></div><span class="${esc(x.status)}">${esc(x.status)}</span></div>`).join(''),pending=c.pending_restart.length?'<span class="warning">PENDING RESTART</span>':'<span class="pass">ACTIVE</span>',cred=s.facilitator_credentials;
document.querySelector('#content').innerHTML=`<section class="panel s4"><h2>Uptime</h2><div class="metric">${esc(o.metrics.uptime_seconds)}s</div></section><section class="panel s4"><h2>Memory</h2><div class="metric">${fmt(o.metrics.process.rss_bytes)}</div></section><section class="panel s4"><h2>Host load</h2><div class="metric">${esc(o.metrics.host.cpu_percent)}%</div></section><section class="panel s8"><h2>Route monitoring</h2><table><tr><th>Route</th><th>Calls</th><th>Errors</th><th>Last</th></tr>${rows}</table></section><section class="panel s4"><h2>Security posture</h2>${checks}</section>
<section class="panel s6"><h2>Runtime configuration</h2><form><label>Public URL</label><input name="public_url" value="${esc(c.public_url)}"><label>Request timeout (seconds)</label><input name="request_timeout_seconds" type="number" value="${esc(c.request_timeout_seconds)}"><label>Maximum download bytes</label><input name="max_download_bytes" type="number" value="${esc(c.max_download_bytes)}"><button>Save runtime settings</button></form></section>
<section class="panel s6"><h2>Service pricing · restart required</h2><form>${['scrape','html_to_md','pdf_parse','chat'].map(n=>`<label>${esc(n.replaceAll('_',' '))} (USDC)</label><input name="price_${n}_usdc" value="${esc(c['price_'+n+'_usdc'])}">`).join('')}<button>Save pricing</button></form></section>
<section class="panel s12"><h2>Payment & facilitator · restart required</h2><form data-sensitive="payment"><div class="row"><div><b>Active: ${esc(c.active.payment_mode)}</b><div class="muted">${esc(c.active.x402_network)}</div></div>${pending}</div><label>Payment mode</label><select name="payment_mode"><option ${c.payment_mode==='disabled'?'selected':''}>disabled</option><option ${c.payment_mode==='x402'?'selected':''}>x402</option></select><label>Network (CAIP-2)</label><input name="x402_network" value="${esc(c.x402_network)}" pattern="eip155:[0-9]+" required><label>Asset contract</label><input name="x402_asset" value="${esc(c.x402_asset)}" pattern="0x[0-9a-fA-F]{40}" required><label>Receiving wallet (public address only)</label><input name="x402_pay_to" value="${esc(c.x402_pay_to)}" pattern="0x[0-9a-fA-F]{40}" required><label>Facilitator URL</label><input name="x402_facilitator" type="url" value="${esc(c.x402_facilitator)}" required><label>Authentication</label><select name="x402_facilitator_auth"><option ${c.x402_facilitator_auth==='none'?'selected':''}>none</option><option ${c.x402_facilitator_auth==='cdp'?'selected':''}>cdp</option></select><p class="muted">Save required credentials first. All changes activate together after restart.</p><button>Save payment settings</button></form></section>
<section class="panel s12"><h2>CDP facilitator credentials</h2><div class="row"><div><b>${cred.configured?'Configured':'Not configured'}</b><div class="muted">Source: ${esc(cred.source)}${cred.key_id_fingerprint?' · Key fingerprint '+esc(cred.key_id_fingerprint):''}</div></div></div>${cred.admin_managed?`<form data-endpoint="facilitator-credentials" data-sensitive="credentials"><label>CDP API key ID</label><input name="api_key_id" required autocomplete="off"><label>CDP API private key</label><input name="api_key_secret" type="password" required autocomplete="new-password"><p class="muted">Stored in the persistent data volume with restricted file permissions; never returned or logged. Prefer an external secret manager for high-assurance deployments.</p><button>Replace credentials</button></form>`:'<p>These credentials are externally managed and cannot be changed here.</p>'}</section>`;document.querySelectorAll('form').forEach(f=>f.onsubmit=save)}
async function save(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));for(const k of['request_timeout_seconds','max_download_bytes'])if(k in data)data[k]=Number(data[k]);if(e.target.dataset.sensitive&&!confirm('Save these sensitive settings? Review every value before restarting FetchHarbor.'))return;try{const body=JSON.stringify(data);if('api_key_secret' in data)data.api_key_secret='';const r=await api(e.target.dataset.endpoint||'configuration',{method:'PUT',body});if(r.restart_required?.length)alert('Restart required for: '+r.restart_required.join(', '));await loadAll()}catch(x){alert(x.message)}finally{e.target.querySelectorAll('input[type=password]').forEach(i=>i.value='')}}
window.addEventListener('DOMContentLoaded',loadAll);
</script></body></html>"""
